### ISSUE TITLE
Select-Room-View

### ISSUE THREAD

**Issue by valentindoering** [hpi-swt2/compass-portal-red#120]
When Im on a Detailpage of a room, I want have the option to see the location of the room marked on the map. From there I want to have the option to either go back to the Detailpage or to start the navigation.

See the Mockups "Show on Map".
![Screenshot 2022-01-04 at 22 27 53](https://user-images.githubusercontent.com/54007786/148126204-1292f02f-50a6-4f79-a325-a4fcda862416.png)
![Screenshot 2022-01-04 at 22 28 03](https://user-images.githubusercontent.com/54007786/148126210-dc5d857a-0977-4f53-bf6e-ba6cfca0f448.png)

# Details
- Input is Room ID, get the coordinates of corners, calculate the point of the marker
- get the Team from the detail page to put a "Show on Map" button on the page
- communicate with the navigation team to set up the navigation button
- To set the marker you need to calculate a center point position of the room (you could also set a new attribute, whichever is easier). Jannis team will put labels (names) on the rooms, for that they will also need a midpoint, they will ask you how you did that. Jannis team would like to make the room names clickable as well, so they will ask how they need to set the link so that our popup shows up

# Tasks
- [x] Build function that returns midpoint of given room_id (maybe extension on room model)
- [x] Build popup layout template
- [x] In e.g. controller, retrieve room information for passed room_id as parameter, fill the popup template with the information
- [x] Display marker on map
- [x] Check that the map centers on the marker (+ zoomed), when a popup is opened.
