### ISSUE TITLE
Update Database Function: scraping tool + data problem documentation

### ISSUE THREAD

**Issue by valentindoering** [hpi-swt2/compass-portal-red#43]
# Goal
- when `update database` is called the scraping script will do its best to update, extend the database
- for everything that is missing towards a filled database, this ticket will come up with good documentation format per database entry, that e.g. mails can be sent

# Requirements
- the scraping script, when triggered updates the applications database automatically
- it should resolve conflicts, when possible
- an attribute of an entry can have 3 types of problems
     - missing data
     - conflicting data (scraping)
     - outdated data (store a last updated timestamp and a default time to life for each entry)
- for problems, that are not resolvable it should create a conflict object per entry, that documents problem, so that it can later be turned into a mail to request resolving from the user

# Notes
- establish mapping from name  in the URL map to database entry to update the right entry
- the script should not build a new database, but update the existing values
- ask the database team for the current version of the database (what tables, what attributes) and mock it (vertical integration)

# Tasks

- [x] Create table for scraping problems: 
    - Entity Id (One nullable foreign key for each entity, room_id, person_id, ... -> only one is set)
    - Problem type (outdated, missing, conflicting)
    - Field (attribute name where the problem occurred)
    - Url (for documentation, the URL where the problem occurred)

- [x] Update person model (@cdfhalle):
    - for each entity attribute (name, room, ...), we need a attribute `human_verified` which contains a timestamp when a user set the attribute manually

- [x] Fill tables (entity + problem) when scraping:
    - Delete problem table when starting to scrape
    - Fill all entity fields (e.g. name, room, telephone), where `human_verified` is not set or outdated
    - If data exists, but human_verified is outdated, save a outdated problem
    - If data is conflicting (updatedAt < 1 day), save a conflicting problem
    - When done, find entities with missing fields and save a missing field for each field

**Comment by lucasliebe** [comment]
check for cascade delete later

**Comment by lucasliebe** [comment]
So far we established the Database changes and prepared some code. The Linter also does not show many errors at the moment. We definitly need to test our functionality and also write tests @alexanderwischmann .

**Comment by lucasliebe** [comment]
cascade may not be needed because table will be cleared later again anyway so we dont need to enforce it

**Comment by lucasliebe** [comment]
functionality is finished, just tests are missing
