### ISSUE TITLE
Resolve user data problems, by contacting them automatically

### ISSUE THREAD

**Issue by valentindoering** [hpi-swt2/compass-portal-red#44]
# Goal
Get the users to update their data, by emailing them and providing a nice user interface to let them do this

# Input
- once in a while the update database function calls the scraper to update the database, but it will never manage to fill the database completely, there will always be problems
- an attribute of an entry can have 3 types of problems
     - missing data
     - conflicting data (scraping)
     - outdated data (store a last updated timestamp and a default time to life for each entry)
- Luckily the update database function will create a problem documentation per entry (#43 )

# Requirements
- use the problem documentation to create a request to the user to resolve the problems (only user table!)
- the request should come in form of an email, should be easy to understand (quick understandable, short precise)
- the user should have the chance to resolve the problems in no time, by filling out the linked online form that explicitly asks for the missing/conflicting data
- the form should automatically trigger the update in the database and resolve the linked problem documentation

# Notes
- ask for permission to send email, is it necessary that the hpi user agrees with getting these emails?
- add a database attribute to toggle sending permission per user
- ask the database team for the current version of the database (what attributes) and mock it (vertical integration)
- this ticket is for people only, places are not covered

# Tasks
- [x] "Email"-Table to log outgoing emails with email address + last_sent
- [x] After scraping, group the problem table by person id (to get all problems per person)
- [x] Send email with link to edit page (optional: use same highlight as in #46) to all persons
- [x] If last_sent is less than 3 months before now, DON'T send an email
- [x] Update last_sent if email is sent

**FOR NOW, send emails only to the sender email address!**

**Comment by tfiedlerdev** [comment]
TODO: 
- [ ] store password of sender email account in encrypted file
- [ ] write tests
