### ISSUE TITLE
Interface to resolve all remaining data problems

### ISSUE THREAD

**Issue by valentindoering** [hpi-swt2/compass-portal-red#46]
# Goal
Provide and interface to resolve all remaining data problems documentation

# Introduction
- once in a while the update database function calls the scraper to update the database, but it will never manage to fill the database completely, there will always be data conflicts or missing data. Luckily the update database function will create a problem documentation per data entry (#43 )
- an attribute of an entry can have 3 types of problems
     - missing data
     - conflicting data
     - outdated data 
- for the user problem documentation in most case there will be an email, that asks the user directly to resolve the problems

# Problem
- after the scraping update, even after emailing users (#44 )  data problems will remain
- we cant reach out to places via email
- especially the initial empty database will have a lot of data problems

# Requirements
- there should be a nice web interface (form) that admin user of our system should be able to see, to resolve the documented database problems
- the database should get updated from the input data of the form
- ask the database team for the current version of the database to mock all of its attributes (vertical integration)

# Tasks

- [x] Use code generated by scaffold in #43 to display table of all problems 
- [x] Add link to edit page for entities
- [x] When a field is changed (and saved), update the `human_verified` timestamp for that attribute
    - **OR** add checkboxes for each `human_verified` which update the timestamp and automatically check when changing a field
- [x] (Optional:) If possible, highlight the field with problem (e.g. URL hash / query param)
