### ISSUE TITLE
Entrances (Full stack)

### ISSUE THREAD

**Issue by jannis-baum** [hpi-swt2/compass-portal-red#88]
> As a user managing data, I want a way of defining entrances to rooms and buildings. As a general user, I want the map to display entrances to rooms and buildings to find my way.

## Context & current state

- the database has a table that can define general "points of interest" such as a sofa by its latitude and longitude coordinates
- the map can display rooms (given by sets of points) and is currently being enhanced to display points of interest (team FNHP)
- rooms can be sketched in JOSM and imported into the database as explained [here](https://github.com/hpi-swt2/compass-portal-red/wiki/Importing-building-plans)

## Tasks / Acceptance

- [ ] add structure to save entrance points to database (e.g. add column `type` to points of interest table that holds one of `entrance`, `point of interest`)
- [ ] create `1-n` relationship between rooms / buildings and entrances in database that can define what entrance is a door to what room / building
- [ ] create a script that takes in a `.gpx` (type of `xml`) file created in JOSM and adds entrance points to the database accordingly (analogues / simplified version of [tutorial (see above)](https://github.com/hpi-swt2/compass-portal-red/wiki/Importing-building-plans) for rooms. The script for rooms is currently in development at team CL, collaboration is desired but not required.)
- [ ] add displaying of entrances to the existing map (analogous to displaying points of interest as being developed at team FNHP)
