### ISSUE TITLE
Map/12 Indoor navigation SPIKE

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#95]
Spike Goal: What is the status of the indoor navigation and how can we implement that in our map?

If I navigate to a location, that is inside, i also want to be giuded inside of the building. This should work with a line on the map, just like with the outdoor navigation and be mostly indifferentiable from it.
- [ ]  Navigation to the best door to enter the building. (Door locations should be provided by another team)
- [ ]  Navigation on the ground floor.
- [ ] Navigation to places on different floors than gound floor.
The customer requested a **80/20** product, it should work well but do not over-engineer it at the wrong place. This story is also epic and can be split into several pieces if you request it.

**Comment by ldreessen** [comment]
closed by PO
